### ISSUE TITLE
is the msrvtt feature corrupted?

### ISSUE THREAD

**Issue by JonnyS1226** [lionel-hing/BiC-Net#2]
hi, I have read your wonderful paper and want to reproduce it.
But when i download the MSRVTT features dataset and unzip it, it shows ‘ cannot find zipfile directory’, and i found that 'msrvtt_region_feature.h5' may be corrupted.
I will really appreciate it that if you can re-check it, thanks.

**Comment by lionel-hing** [comment]
Ok, we'll re-upload a MSR-VTT.zip file soon. I'll let you know later.

**Comment by lionel-hing** [comment]
You can download MSR-VTT again. @JonnyS1226

**Comment by JonnyS1226** [comment]
Sorry, but i still cannot unzip it after download. Is there anyone else face the same problem? I wonder if it is my mistake.

**Comment by lionel-hing** [comment]
We have tried it on linux and windows systems and it works.  Is there an error in the download process?  

Below is the download link for the video feature separation.

Global features: https://drive.google.com/file/d/18QpP43gQp9BIf7PUpfQHkQ59Aycwvelh/view?usp=sharing.  
Region features: https://drive.google.com/file/d/1uZRlRyKGkoB1Fbwm_pz89Kn94sijsdla/view?usp=sharing

I don't know if it was possible to decompress the text features before. If not, I'll post the link later when I upload it.

**Comment by JonnyS1226** [comment]
Really thanks. My OS is mac OS, or may have some error in download process. I will try it again.

**Comment by JonnyS1226** [comment]
I have fixed it. It is because that MacOS may get stuck in unzipping huge zip file. Trying it via 7z, jar, or ditto may solve the problem.
Really thanks for your patience!
